Importing necessary libraries

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix, accuracy_score

Reading the dataset with Pandas after mounting the dataset in google colab

In [ ]:
#reading the dataset with a dataframe
df = pd.read_csv("final_preprocessed_dataset.csv")

In [ ]:
#eye balling the data
df.head(5)

Resource  ... APTGroup
0  4d74c8da7274bb56bab01f47334a9551f57a6dcf  ...        9
1  cc221465dac981f4934fef39d41ddb2e1d26299f  ...        3
2  a49718feddf874a62049809af51e858ad41897c4  ...        0
3  78c00614535b949770708069615764d0155cad76  ...       10
4  44787ddf91b10291f8338590c5d99839040e1cd5  ...        3

[5 rows x 151 columns]

Converting the Apt Groups to numbers for running properly in the classifier model. This is our lablled column for using the supervised learning technique

In [ ]:
df['APT Group'] = LabelEncoder().fit_transform(df['APT Group'])
df['APT Group'].max()
df.head(5)

Resource  ...  APTGroup
0  4d74c8da7274bb56bab01f47334a9551f57a6dcf  ...         9
1  cc221465dac981f4934fef39d41ddb2e1d26299f  ...         3
2  a49718feddf874a62049809af51e858ad41897c4  ...         0
3  78c00614535b949770708069615764d0155cad76  ...        10
4  44787ddf91b10291f8338590c5d99839040e1cd5  ...         3

[5 rows x 151 columns]

Dropping resource column

In [ ]:
df = df.drop('Resource', 1)

In [ ]:
#eye balling information about our dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2862 entries, 0 to 2861
Columns: 150 entries, APT Group to APTGroup
dtypes: float64(1), int64(149)
memory usage: 3.3 MB


Sklearn Train Test Split Method

In [ ]:
#the labelled column is Apt Group and the rest is features
label = np.array(df['APT Group'])
features = df.drop('APT Group',1)

In [ ]:
#choosing a 70-30 split to test out the performance
seed =50
X_train, X_test, y_train, y_test = train_test_split(features,label,test_size=0.30, random_state = seed)

In [ ]:
X_train.dtypes

Entry Point                           float64
'ACTIVEDS.DLL'                          int64
'ADVAPI32.DLL'                          int64
'API-MS-WIN-CRT-HEAP-L1-1-0.DLL'        int64
'API-MS-WIN-CRT-LOCALE-L1-1-0.DLL'      int64
                                       ...   
'SORBIAN DEFAULT'                       int64
'SPANISH MODERN'                        int64
'SWEDISH'                               int64
'TURKISH DEFAULT'                       int64
APTGroup                                int64
Length: 149, dtype: object

In [ ]:
X_train

Entry Point  'ACTIVEDS.DLL'  ...  'TURKISH DEFAULT'  APTGroup
800       83741.0               0  ...                  0         4
2684    1079966.0               0  ...                  0        10
64        24146.0               0  ...                  0         0
1010     180864.0               0  ...                  0        11
2360     430686.0               0  ...                  0        10
...           ...             ...  ...                ...       ...
2014       8082.0               0  ...                  0         7
2157     139788.0               0  ...                  0         4
1931     163658.0               0  ...                  0        10
1504     140242.0               0  ...                  0         8
1712      32239.0               0  ...                  0         6

[2003 rows x 149 columns]

In [ ]:
X_test.dtypes

Entry Point                           float64
'ACTIVEDS.DLL'                          int64
'ADVAPI32.DLL'                          int64
'API-MS-WIN-CRT-HEAP-L1-1-0.DLL'        int64
'API-MS-WIN-CRT-LOCALE-L1-1-0.DLL'      int64
                                       ...   
'SORBIAN DEFAULT'                       int64
'SPANISH MODERN'                        int64
'SWEDISH'                               int64
'TURKISH DEFAULT'                       int64
APTGroup                                int64
Length: 149, dtype: object

In [ ]:
X_test

Entry Point  'ACTIVEDS.DLL'  ...  'TURKISH DEFAULT'  APTGroup
1688      23536.0               0  ...                  0         0
2455      10136.0               0  ...                  0        11
2716     470572.0               0  ...                  0        10
2296      10710.0               0  ...                  0         1
578      549060.0               0  ...                  0        10
...           ...             ...  ...                ...       ...
2509      27988.0               0  ...                  0         0
722       54299.0               0  ...                  0         9
2178       5938.0               0  ...                  0         4
1616       9072.0               0  ...                  0         1
673        9072.0               0  ...                  0         1

[859 rows x 149 columns]

Building the Random Forest Classifier

In [ ]:
rf_classifier = RandomForestClassifier(
                      min_samples_leaf=50,
                      n_estimators=150,
                      bootstrap=True,
                      oob_score=True,
                      n_jobs=-1,
                      random_state=seed,
                      max_features='auto')

In [ ]:
rf_classifier.fit(X_train,y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=50, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=150,
                       n_jobs=-1, oob_score=True, random_state=50, verbose=0,
                       warm_start=False)

In [ ]:
y_pred = rf_classifier.predict(X_test)

In [ ]:
print(y_pred)

[ 0 11 10  1 10  9 10  9  6  7  9 10 11 11 11  0  9  9  9 11  9  9 10  7
  7  5  5  5  5  0  0  5  5  9  0  8 10 11  1  7 11 10 11  7  1  0 11 11
  9 11 11 11  5  9  0  0 10  5  5 11  7  1  0  0 10 11 11  5 11  7 10  8
  0  9  1  9 10  1 10 10 10 11  5 11  0  0  9  0 11  8  9  0  5 11  9  7
  5 10 11  9  9  5 10  5 11 11 11  7  5  8 11 11  8 11  9  9  8  9  0 10
  7  1 11  0 10 11  7  5 11 11 11  9  0 10 11  0  7  5 11 11  0  0  0  7
 11  5  7  0  9 11  0  1  5 11  8 10  0  0  9  5 11  9  5 11 10  9  1  9
 10  1  1 11  7 11  9 11  9  5  5  7 10 11 11 10 11 11  9 11 11 10 11  0
  9 11 10  1  8  5  0 10  9  9 10  1  9  0 10 10  9  0 10 11  5  5  1 10
  0  5 10  9  0 10  9  5  5  0  0  0  5 11 10 11  7  9  0  0 11 11  1 11
 10  7  7 11 11 11 10 10  7  5 11 11 11  7  1 10 11  5  9  0  5 10  0 11
  0  9  8 11  5  8 10 11 11  6 11 10  5 11 11  7  0  7  7 10  5  9  0  9
  0 11  5  9  0  7 10 11 11  8 11  8 11  9  7  1  0  9  0  5  7  9 10  5
  0 10 11  0  1  9 10  5 11  9 10  0  0  5 11  0 11

Confusion Matrix

In [ ]:
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[126   0   0   0   0   0   0   0   0   0   0   0]
 [  2  46   0   0   0   4   0   2   0   4   2   2]
 [  2   0   0   0   0   0   0   6   0   0   2   0]
 [  0   7   0   0   0   7   0   0   0   0   1  13]
 [  9   3   0   0   0  14   0   4   0   3   2  11]
 [  4   0   0   0   0  51   0   5   2   2  14   3]
 [  4   1   0   0   0   5  11   1   0   6   0  22]
 [  6   1   0   0   0  14   0  46   0   3   9   7]
 [  0   0   0   0   0   0   0   1  39   0   1   0]
 [  0   0   0   0   0   0   0   0   0 113   0   0]
 [  0   0   0   0   0   0   0   0   0   2  90   2]
 [  0   0   0   0   0   0   0   0   0   0   0 122]]


0.7497089639115251

# Observation:

Accuracy acquired about 75% accuracy. Needs more hyperparameter tuning to increase the accuracy. Maybe contributing other factors along the way too can lead to better accuracy.

## Model Attempt#2

In [ ]:
"""
rf_classifier = RandomForestClassifier(
                      min_samples_leaf=50,
                      n_estimators=150,
                      bootstrap=True,
                      oob_score=True,
                      n_jobs=-1,
                      random_state=seed,
                      max_features='auto')
                      """
rf_classifier = RandomForestClassifier(
                      min_samples_leaf=3,
                      n_estimators=300,
                      bootstrap=True,
                      oob_score=True,
                      n_jobs=-1,
                      random_state=seed,
                      max_features='auto')

In [ ]:
rf_classifier.fit(X_train,y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=3, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=300,
                       n_jobs=-1, oob_score=True, random_state=50, verbose=0,
                       warm_start=False)

In [ ]:
y_pred = rf_classifier.predict(X_test)

In [ ]:
print(y_pred)

In [ ]:
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[126   0   0   0   0   0   0   0   0   0   0   0]
 [  1  56   0   0   1   0   1   0   0   1   2   0]
 [  1   0   2   0   3   1   0   3   0   0   0   0]
 [  0   8   0  12   0   6   1   0   0   0   0   1]
 [  2   2   0   0  36   4   1   0   0   0   1   0]
 [  0   0   0   0   1  80   0   0   0   0   0   0]
 [  0   1   0   0   0   0  46   1   0   0   0   2]
 [  0   1   0   0   0  17   0  63   0   0   5   0]
 [  0   0   0   0   0   0   0   0  41   0   0   0]
 [  0   0   0   0   0   0   0   0   0 113   0   0]
 [  0   0   0   0   0   0   0   0   0   0  93   1]
 [  0   0   0   0   0   0   0   0   0   0   0 122]]


0.919674039580908

Accuracy is 0.919674039580908 -

# Observation 2:

Accuracy acquired about 91.9% accuracy.